// USER

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR'

export const SET_USERS_PENDING = 'SET_USERS_PENDING'
export const SET_USERS_ERROR = 'SET_USERS_ERROR'
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS'

// PROJECT

export const SET_PROJECTS_PENDING = 'SET_PROJECTS_PENDING'
export const SET_PROJECTS_SUCCESS = 'SET_PROJECTS_SUCCESS'
export const SET_PROJECTS_ERROR = 'SET_PROJECTS_ERROR'

// FETCH JOB

export const SET_FETCH_JOBS_PENDING = 'SET_FETCH_JOBS_PENDING'
export const SET_FETCH_JOBS_SUCCESS = 'SET_FETCH_JOBS_SUCCESS'
export const SET_FETCH_JOBS_ERROR = 'SET_FETCH_JOBS_ERROR'

// INFLUENCER

export const SET_INFLUENCERS_SUCCESS = 'GET_ALL_INFLUENCERS_SUCCESS'
export const SET_INFLUENCERS_PENDING = 'GET_ALL_INFLUENCERS_PENDING'
export const SET_INFLUENCERS_ERROR = 'GET_ALL_INFLUENCERS_ERROR'


// MEDIA FETCH

export const GET_MEDIA_BY_HASHTAG_SUCCESS = 'GET_MEDIA_BY_HASHTAG_SUCCESS'
export const GET_MEDIA_BY_HASHTAG_ERROR = 'GET_MEDIA_BY_HASHTAG_ERROR'
export const GET_MEDIA_BY_HASHTAG_PENDING = 'GET_MEDIA_BY_HASHTAG_PENDING'

// NEXT PAGE FETCH
export const GET_MEDIA_NEXT_PAGE_PENDING = 'GET_MEDIA_NEXT_PAGE_PENDING'
export const GET_MEDIA_NEXT_PAGE_SUCCESS = 'GET_MEDIA_NEXT_PAGE_SUCCESS'
export const GET_MEDIA_NEXT_PAGE_ERROR = 'GET_MEDIA_NEXT_PAGE_ERROR'
export const GET_MEDIA_NEXT_PAGE_COMPLETED = 'GET_MEDIA_NEXT_PAGE_COMPLETED'


// USER FETCH
export const GET_USER_PENDING = 'GET_USER_PENDING'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const COMPLETED_GET_ALL_USERS = 'COMPLETED_GET_ALL_USERS'

// COLLAB

export const SET_COLLABS_PENDING = 'SET_COLLABS_PENDING'
export const SET_COLLABS_SUCCESS = 'SET_COLLABS_SUCCESS'
export const SET_COLLABS_ERROR = 'SET_COLLABS_ERROR'

export const GET_USER_MEDIA_PENDING = 'GET_USER_MEDIA_PENDING'
export const GET_USER_MEDIA_SUCCESS = 'GET_USER_MEDIA_SUCCESS'
export const GET_USER_MEDIA_ERROR = 'GET_USER_MEDIA_ERROR'